#!/usr/bin/env bash
# Cross-compiles src/FlowSwitch/Shaders/FlowSwitch.hlsl (the exact shaders the Windows renderer
# uses) to GLSL ES 3.00 for the WebGL design preview:  HLSL → SPIR-V (glslang) → GLSL (spirv-cross).
# Also acts as a syntax/semantics check of the HLSL on non-Windows machines.
set -euo pipefail
here="$(cd "$(dirname "$0")" && pwd)"
src="$here/../../src/FlowSwitch/Shaders/FlowSwitch.hlsl"
gen="$here/generated"
tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT
mkdir -p "$gen"

entries=(VSQuad:vert VSFullscreen:vert PSBackdrop:frag PSCard:frag PSSprite:frag PSGlow:frag PSOrbit:frag PSPill:frag)
out="$gen/shaders.js"
echo "// Generated by build-shaders.sh — do not edit." > "$out"
echo "export const shaders = {" >> "$out"
for e in "${entries[@]}"; do
  name="${e%%:*}"; stage="${e##*:}"
  glslangValidator -D -V -S "$stage" -e "$name" --auto-map-bindings "$src" -o "$tmp/$name.spv" > "$tmp/$name.log" || { cat "$tmp/$name.log"; exit 1; }
  if [ "$stage" = vert ]; then
    rename=(--rename-interface-variable out 0 v_local --rename-interface-variable out 1 v_screen)
  else
    rename=(--rename-interface-variable in 0 v_local --rename-interface-variable in 1 v_screen)
  fi
  glsl="$(spirv-cross --es --version 300 "${rename[@]}" "$tmp/$name.spv" | sed "s/precision mediump float;/precision highp float;/")"
  printf '  %s: %s,\n' "$name" "$(printf '%s' "$glsl" | python3 -c 'import json,sys; print(json.dumps(sys.stdin.read()))')" >> "$out"
done
echo "};" >> "$out"
echo "wrote $out"
